project:
  type: website

website:
  title: "Quang Huy Nguyen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor_options: 
  chunk_output_type: console

